### ISSUE TITLE
Nightly CI rviz_default_plugins failed to build on OSX

### ISSUE THREAD

**Issue by tfoote** [ros2/rviz#683] opened 2021-05-10 21:47 UTC
The nightly repeated job failed to build last night: https://ci.ros2.org/job/nightly_osx_repeated/2339/console

stdout:

```
01:38:54 [ 38%] Building CXX object CMakeFiles/rviz_default_plugins.dir/src/rviz_default_plugins/displays/marker/marker_common.cpp.o
01:38:54 make[1]: *** [CMakeFiles/rviz_default_plugins.dir/all] Alarm clock: 14
01:38:54 make: *** [all] Error 2
```

stderr:

```
--- stderr: rviz_default_plugins
01:38:54 /Users/osrf/jenkins-agent/workspace/nightly_osx_repeated/ws/src/ros2/rviz/rviz_default_plugins/include/rviz_default_plugins/displays/image/get_transport_from_topic.hpp:0: Note: No relevant classes found. No output generated.
01:38:54 /Users/osrf/jenkins-agent/workspace/nightly_osx_repeated/ws/src/ros2/rviz/rviz_default_plugins/include/rviz_default_plugins/displays/image/image_transport_display.hpp:0: Note: No relevant classes found. No output generated.
01:38:54 make[1]: *** [CMakeFiles/rviz_default_plugins.dir/all] Alarm clock: 14
01:38:54 make: *** [all] Error 2
01:38:54 make: INTERNAL: Exiting with 3 jobserver tokens available; should be 4!
01:38:54 ---
01:38:54 Failed   <<< rviz_default_plugins [6min 9s, exited with code 2]
```

**Comment by clalancette** [comment] 2021-05-17 21:13
This one is a duplicate of https://github.com/ros2/ros2/issues/1049 (and is a bug in make itself).  I'll close this as a duplicate.

**Closed as completed by clalancette** 2021-05-17 21:13 UTC
