### ISSUE TITLE
ros2-dashing-debug windows rviz2 ERROR

### ISSUE THREAD

**Issue by cjsJack** [ros2/rviz#492] opened 2019-12-11 04:11 UTC
I am using ros2-dashing-debug in windows, using vs2017, when I command rviz2, it appear some error:

```
C:\Windows\System32>rviz2
[INFO] [rviz2]: Stereo is NOT SUPPORTED
[INFO] [rviz2]: OpenGl version: 4.6 (GLSL 4.6)
[INFO] [rviz2]: Stereo is NOT SUPPORTED
[ERROR] [rviz2]: Could not load pixmap package://rviz_common/icons/rotate.svg -- using default cursor instead.
[ERROR] [rviz2]: Could not load pixmap package://rviz_common/icons/rotate_cam.svg -- using default cursor instead.
[ERROR] [rviz2]: Could not load pixmap package://rviz_common/icons/move2d.svg -- using default cursor instead.
[ERROR] [rviz2]: Could not load pixmap package://rviz_common/icons/move_z.svg -- using default cursor instead.
[ERROR] [rviz2]: Could not load pixmap package://rviz_common/icons/zoom.svg -- using default cursor instead.
[ERROR] [rviz2]: Could not load pixmap package://rviz_common/icons/crosshair.svg -- using default cursor instead.
[ERROR] [rviz2]: Could not load pixmap package://rviz_common/icons/crosshair.svg -- using default cursor instead.
[ERROR] [rviz2]: Could not load pixmap package://rviz_common/icons/crosshair.svg -- using default cursor instead.
[ERROR] [rviz2]: Could not load pixmap package://rviz_common/icons/rotate.svg -- using default cursor instead.
[ERROR] [rviz2]: Could not load pixmap package://rviz_common/icons/rotate_cam.svg -- using default cursor instead.
[ERROR] [rviz2]: Could not load pixmap package://rviz_common/icons/move2d.svg -- using default cursor instead.
[ERROR] [rviz2]: Could not load pixmap package://rviz_common/icons/move_z.svg -- using default cursor instead.
[ERROR] [rviz2]: Could not load pixmap package://rviz_common/icons/zoom.svg -- using default cursor instead.
[ERROR] [rviz2]: Could not load pixmap package://rviz_common/icons/crosshair.svg -- using default cursor instead.
```

But rviz can also succeed showing the window, so it is normal, or I should add some dll path, 
thanks,

**Comment by wjwwood** [comment] 2020-01-02 17:38
Did you source the `setup.bat` file? Please give more details on how to reproduce your issue.

I'm going to close this because I believe the issue has been addressed. Feel free to continue to comment and I can reopen if necessary.

**Closed as completed by wjwwood** 2020-01-02 17:38 UTC

**Comment by kelebujiabing** [comment] 2020-03-28 10:58
![image](https://user-images.githubusercontent.com/10735902/77821552-3760ad00-7126-11ea-8af6-cc855475d928.png)


hi, I meet the same errs. And source the setup.bat doesn't work for me.pls help, thanks

**Comment by cjsJack** [comment] 2020-03-31 10:51
I am sorry, I don't know how to solve this problem, but  this problem
doesn't effect we use this version.

kelebujiabing <notifications@github.com> 于2020年3月28日周六 下午6:58写道：
