### ISSUE TITLE
Unable to build downstream rviz plugins using fat binaries

### ISSUE THREAD

**Issue by clalancette** [ros2/rviz#556] opened 2020-06-02 18:32 UTC
With the current setup of `rviz*` packages, it isn't currently possible to build rviz plugins outside of this main repository when using fat binaries.

To reproduce this:
```
$ wget https://ci.ros2.org/view/packaging/job/packaging_linux/1887/artifact/ws/ros2-package-linux-x86_64.tar.bz2
$ tar -xvf ros2-package-linux-x86_64.tar.bz2
$ source ros2-linux/setup.bash
$ mkdir -p nav2_ws/src
$ cd nav2_ws/src
$ git clone https://github.com/BehaviorTree/BehaviorTree.CPP.git -b master
$ git clone https://github.com/ros-planning/navigation2.git -b master
$ cd ../..
$ colcon build --packages-up-to nav2_rviz_plugins
```

The output I get when building `nav2_rviz_plugins` is:
```
CMake Error in CMakeLists.txt:
  Imported target "rviz_common::rviz_common" includes non-existent path

    "/home/jenkins-agent/workspace/packaging_linux/ws/install/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```

This looks like artifacts from the packaging machine, so should not be in the exported cmake path.

**Comment by dirk-thomas** [comment] 2020-06-02 20:56
The problem is due to ros2/rviz#537. There are more dependencies of `rviz_common` which don't export modern CMake target and therefore the exported target of `rviz_common` is *not* relocatable.

**Comment by dirk-thomas** [comment] 2020-06-02 21:12
I am pretty sure this is a duplicate of #554 in that the root cause is the same. Depending on what dependency doesn't export modern CMake targets different absolute paths are the issue. Ultimately in order for the rviz packages to be relocatable while they export targets all dependencies must export modern CMake targets too.

**Comment by dirk-thomas** [comment] 2020-06-03 14:24
> Imported target "rviz_common::rviz_common" includes non-existent path

This problem is resolved for me with the referenced PRs. It is easy to confirm since the generated `rviz_commonExport.cmake` file doesn't contain any absolute paths anymore.

That being said `master` (unrelated to the referenced PRs) shows a new absolute path in `rclExport.cmake` which results in these errors:

```
Imported target "rclcpp::rclcpp" includes non-existent path
Imported target "rclcpp_action::rclcpp_action" includes non-existent path
Imported target "rclcpp_lifecycle::rclcpp_lifecycle" includes non-existent path
```

**Comment by dirk-thomas** [comment] 2020-06-04 03:51
> That being said `master` (unrelated to the referenced PRs) shows a new absolute path in `rclExport.cmake` which results in these errors:

This seems to be solved in the latest packaging build from `master`.

But... of course there is another one containing absolute paths:

```
Imported target "rviz_common::rviz_common" includes non-existent path
  "/home/jenkins-agent/workspace/ci_packaging_linux/ws/install/opt/rviz_ogre_vendor/include/OGRE"
```

**Comment by dirk-thomas** [comment] 2020-06-04 04:11
Imported target "rviz_common::rviz_common" includes non-existent path
      "/home/jenkins-agent/workspace/ci_packaging_linux/ws/install/opt/rviz_ogre_vendor/include/OGRE"

Resolved by ros2/rviz#558.

But... of course there is yet another one containing absolute paths:

```
Imported target "rviz_default_plugins::rviz_default_plugins" includes non-existent path
  "/home/dthomas/ros2/head/ws/install/interactive_markers/include"
```

**Comment by dirk-thomas** [comment] 2020-06-04 04:18
Imported target "rviz_default_plugins::rviz_default_plugins" includes non-existent path
      "/home/dthomas/ros2/head/ws/install/interactive_markers/include"

Resolved by ros-visualization/interactive_markers#70.

But... no but this time :wink: This finally makes the build described in the original description pass.

**Comment by dirk-thomas** [comment] 2020-06-04 05:38
I am going to close this ticket under the assumption that the problem has been resolved.

**Closed as completed by dirk-thomas** 2020-06-04 05:38 UTC
Labels: bug
