### ISSUE TITLE
PointCloud2 and Other Topics no longer Display in RVIZ after upgrade from FOXY Release 5 to FOXY Release 6

### ISSUE THREAD

**Issue by tomcat327** [ros2/rviz#782] opened 2021-10-08 19:31 UTC
Today, I "apt upgraded" to FOXY Patch Release 6, which came out on Oct. 7, 2021. Previously, I had been on FOXY Patch Release 5, which came out on Sept. 9, 2021. See this link for patch release details: https://github.com/ros2/ros2/releases.

For over a year, I have been using an rviz configuration file ([ouster_live.zip](https://github.com/ros2/rviz/files/7313693/ouster_live.zip)) with RVIZ2 to watch PointCloud2s coming from "ros2 bag play". This is all managed within a launch file.

However, after the upgrade to 6, I can no longer visualize PointCloud2s in RVIZ2. 

Here is a PointCloud2-less screenshot showing no point clouds on the left and the results of "ros2 topic info -v /MAP_LiDAR/PointCloud2" on the right:
![NoPointCloudVisible](https://user-images.githubusercontent.com/59889464/136614398-7d832eed-5c5b-4b16-9586-ea207fb4b348.png)

The result of "ros2 topic echo /MAP_LiDAR/PointCloud2" is shown below, proving that PointCloud2s are definitely being published:
![PointCloudDefinitelyPublished](https://user-images.githubusercontent.com/59889464/136614819-e2f7f4c0-5b18-4e37-a416-5276a7559ec1.png)

For this issue, I'm focusing on PointCloud2s, but I am also having the same problem with visualization of Path and Pose topics. This seems to be a bug, but if it is user error, I apologize in advance. Something seems to have changed (external to my unchanged setup) in the last month that is causing these issues. Thank you in advance!

**Comment by gbalke** [comment] 2021-10-08 20:48
Verified. I'll start taking a look. @jacobperron any guesses?

**Comment by jacobperron** [comment] 2021-10-08 20:51
@gbalke I would start by doing a bisect between 8.2.3 and 8.2.4 to find an offending commit: https://github.com/ros2/rviz/commits/foxy

**Comment by gbalke** [comment] 2021-10-08 21:14
#772 still displays point clouds.
```
commit cc1e0623c4e3d50d8a9394df052b7a7d8f71068a (HEAD)
```

#765 does not :cry: 
```
commit 154feac780992b26f00f6341eaeee8313a1a30f3 (HEAD)
```

**Comment by gbalke** [comment] 2021-10-08 21:26
@tomcat327 fix is on the way :smiley:

**Comment by tomcat327** [comment] 2021-10-08 21:54
Thank you for the fast response @gbalke!

**Comment by gbalke** [comment] 2021-10-08 22:08
Root caused the problem... Pretty interesting tbh :thinking:
https://github.com/ros2/rviz/pull/783#issuecomment-939139321

**Comment by kallaspriit** [comment] 2021-10-09 10:31
Can also confirm this, pulling out my hair why stuff broke that was working yesterday without changing anything :)

How could one revert to the previous version while this gets fixed? I'm using `ros-foxy-rviz2` package on Ubuntu 20.04.

```
$ apt info ros-foxy-rviz2
Package: ros-foxy-rviz2
Version: 8.2.4-1focal.20211006.001624
Priority: optional
Section: misc
Maintainer: Jacob Perron <jacob@openrobotics.org>
Installed-Size: 92.2 kB
Depends: libc6 (>= 2.14), libgcc-s1 (>= 3.0), libqt5core5a (>= 5.12.2), libqt5widgets5 (>= 5.0.2), libstdc++6 (>= 5.2), ros-foxy-rviz-common, ros-foxy-rviz-default-plugins, ros-foxy-rviz-ogre-vendor, ros-foxy-ros-workspace
Homepage: https://github.com/ros2/rviz/blob/ros2/README.md
Download-Size: 12.6 kB
APT-Manual-Installed: yes
APT-Sources: http://packages.ros.org/ros2/ubuntu focal/main amd64 Packages
Description: 3D visualization tool for ROS.
```

Tried listing old versions but it shows none, doing it wrong?
```
$ apt-cache madison ros-foxy-rviz2
ros-foxy-rviz2 | 8.2.4-1focal.20211006.001624 | http://packages.ros.org/ros2/ubuntu focal/main amd64 Packages
```

Tried cloning tag `8.2.3` into my workspace and `colcon build` it but the build fails.
```
[Processing: rviz_default_plugins]                                         
--- stderr: rviz_default_plugins                                           
/usr/bin/ld: CMakeFiles/point_cloud2_display_test.dir/test/rviz_default_plugins/displays/pointcloud/point_cloud2_display_test.cpp.o: in function `rviz_common::MessageFilterDisplay<sensor_msgs::msg::PointCloud2_<std::allocator<void> > >::incomingMessage(std::shared_ptr<sensor_msgs::msg::PointCloud2_<std::allocator<void> > const>)':
point_cloud2_display_test.cpp:(.text._ZN11rviz_common20MessageFilterDisplayIN11sensor_msgs3msg12PointCloud2_ISaIvEEEE15incomingMessageESt10shared_ptrIKS5_E[_ZN11rviz_common20MessageFilterDisplayIN11sensor_msgs3msg12PointCloud2_ISaIvEEEE15incomingMessageESt10shared_ptrIKS5_E]+0x59): undefined reference to `rviz_common::_RosTopicDisplay::typeErasedMessageTaken(std::shared_ptr<void const>)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/point_cloud2_display_test.dir/build.make:254: point_cloud2_display_test] Error 1
make[1]: *** [CMakeFiles/Makefile2:380: CMakeFiles/point_cloud2_display_test.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/bin/ld: CMakeFiles/point_cloud_scalar_display_test.dir/test/rviz_default_plugins/displays/pointcloud/point_cloud_scalar_display_test.cpp.o: in function `rviz_common::MessageFilterDisplay<sensor_msgs::msg::Illuminance_<std::allocator<void> > >::incomingMessage(std::shared_ptr<sensor_msgs::msg::Illuminance_<std::allocator<void> > const>)':
point_cloud_scalar_display_test.cpp:(.text._ZN11rviz_common20MessageFilterDisplayIN11sensor_msgs3msg12Illuminance_ISaIvEEEE15incomingMessageESt10shared_ptrIKS5_E[_ZN11rviz_common20MessageFilterDisplayIN11sensor_msgs3msg12Illuminance_ISaIvEEEE15incomingMessageESt10shared_ptrIKS5_E]+0x59): undefined reference to `rviz_common::_RosTopicDisplay::typeErasedMessageTaken(std::shared_ptr<void const>)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/point_cloud_scalar_display_test.dir/build.make:238: point_cloud_scalar_display_test] Error 1
make[1]: *** [CMakeFiles/Makefile2:584: CMakeFiles/point_cloud_scalar_display_test.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
---
Failed   <<< rviz_default_plugins [2min 20s, exited with code 2]
```
So how do I revert to the working version or just have to wait for the fix to land in `ros-foxy-rviz2`?

---

EDIT

Commented out the offending (failing to build) tests on the 8.2.3 branch and got it working for now.

**Comment by chenwh14** [comment] 2021-10-10 07:24
I'm also a victim of this version update.
Thank you very much for pulling me out of meaningless attempts....

**Comment by fantauzzi** [comment] 2021-10-10 08:37
I think I am having the same issue in Rviz2 with /scan and /map since the update to patch release 6: Rviz2 doesn't show the LaserScan from a Turtblebot 3 (real or simulated in Gazebo), nor the map being built by cartographer.

[UPDATE] After uninstalling and reinstalling Foxy (via Debian packages) multiple times, eventually Rviz2 resumed receiving /scan and /map and displaying the map being built by cartographer.

**Comment by aprotyas** [comment] 2021-10-10 08:58
> How could one revert to the previous version while this gets fixed? I'm using `ros-foxy-rviz2` package on Ubuntu 20.04.

You can uninstall the Debian packages using `sudo apt remove ~nros-foxy-* && sudo apt autoremove`, and then install previous release binary packages from https://github.com/ros2/ros2/releases. ([Installation instruction for reference](https://docs.ros.org/en/foxy/Installation/Ubuntu-Install-Binary.html))

**Comment by yonhdee** [comment] 2021-10-11 05:00
victim+1, thank you for fast response

**Comment by Paul-Ajay** [comment] 2021-10-11 08:25
Any temporary solution available? until the release of binaries with fix?

**Comment by el-stinjo** [comment] 2021-10-11 15:10
Also ran into this issue, downgrading the entire foxy as proposed by @aprotyas works for me! (although is somewhat time consuming)

**Comment by gbalke** [comment] 2021-10-11 18:05
Revert merged on the problematic code. Actually getting this into a release will take some time given the length of the process so please use the solution posted by @aprotyas or build rviz from source as an overlay until that comes in. I'll be leaving this issue open for visibility.

https://github.com/ros2/rviz/issues/782#issuecomment-939434331

**Comment by gavanderhoorn** [comment] 2021-10-12 14:26
> Actually getting this into a release will take some time given the length of the process

this seems like a serious enough regression to warrant an out-of-band patch release?

**Comment by gbalke** [comment] 2021-10-12 16:57
> this seems like a serious enough regression to warrant an out-of-band patch release?

This is the intended form of release (ASAP).

**Comment by gavanderhoorn** [comment] 2021-10-12 16:59
Great to hear.

I'm actually quoting you in https://github.com/ros2/rviz/issues/782#issuecomment-941063747, so your last comment confuses me ;)

**Comment by gbalke** [comment] 2021-10-12 17:01
I was referring to the time it takes to build a full release and get that process rolling. I understand your confusion though, I should've been more specific.

**Comment by ros-discourse** [comment] 2021-10-12 17:01
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/preparing-for-foxy-sync-and-patch-release-2021-10-13/22664/1

**Comment by ros-discourse** [comment] 2021-10-13 21:13
This issue has been mentioned on **ROS Discourse**. There might be relevant details there:

https://discourse.ros.org/t/new-packages-and-patch-release-for-foxy-fitzroy-2021-10-13/22678/1

**Comment by jacobperron** [comment] 2021-10-13 21:23
A new sync and patch release have been made with #783. Let me know if there you run into any issues.

https://discourse.ros.org/t/new-packages-and-patch-release-for-foxy-fitzroy-2021-10-13/22678

**Closed as completed** 2021-10-13 21:23 UTC
Labels: bug

**Comment by Swapnil-S-Pawar** [comment] 2024-11-19 09:35
I am having the same issue but with Ros2 Humble. Any suggestions, how to resolve this?

**Comment by nbbrooks** [comment] 2025-10-30 18:23
The last message on this is quite old but I am going to link this related issue in case other people come across it.

https://github.com/ros2/rviz/issues/1616
