### ISSUE TITLE
laser scans not showing when fixed frame is not equal to the laser scans frame id

### ISSUE THREAD

**Issue by wjwwood** [ros2/rviz#332] opened 2018-06-28 23:46 UTC
I see this on Ubuntu 18.04 with the bouncy deb binaries.

Steps to reproduce:

- `ros2 launch dummy_robot_bringup dummy_robot_bringup.launch.py`
- `rviz2`
- Add a display by topic and use `/scan`
- Add the tf display
- Add a map display for `/map`
- Set the fixed frame to `world`

You'll see the map and the tf frames moving, but no laser scan. If you look at the laser display you'll see that the status is `Ok`, but the Points field just says `Showing [0] points from [0] messages` and it is not rendered. I would expect it to be rendered.

If you change the fixed frame to `single_rrbot_hokuyo_link` you can see the laser scans and the status adds the `Transform: Ok` status. However, the map no longer renders and prints to the console `[ERROR] [rviz2]: Error transforming map 'Map' from frame 'world' to 'single_rrbot_hokuyo_link'.` and it also sets a similar message, `Could not transform from [world] to [single_rrbot_hokuyo_link]` in the status part of the map display.

My expectation is that both the laser and map should work in either (or any) fixed frame.

**Comment by Martin-Idel-SI** [comment] 2018-06-29 07:27
The main problem seems to be a missing transform. Could you publish a static transform from [world] to e.g. [single_rrbot_hokuyo_link] (or any tf frame of the robot)? I'll have to update my ros2 installation again before I can reproduce. 

The TF display should also show this, are there any warnings with fixed frame [world] or [single_rrbot_hokuyo_link]?

The current behaviour is that we only show displays if there is a transform available between the fixed frame and the frame of the part to show (i.e. `lookupTransform(...)` returns `true`). It seems that the transform between [world] and [single_rrbot_hokuyo_link] is not available in tf2, so we can't really know how to position the map.

The same is probably true for the laser scan display. The behaviour that I want is that it also shows the same status error (and prints to the console). This should have been done in #292 but the laser scan display wasn't touched, so I missed it. 
That part at least is a bug in rviz and I'll prepare a PR to fix it.

**Comment by wjwwood** [comment] 2018-06-29 07:47
There are correct transforms from world to the laser frame, but they’re not all static transforms. This use case should work and it did work in the past, I used this demo before to show the laser scans moving at the end of the tf tree which waving back and forth.

**Comment by wjwwood** [comment] 2018-06-29 07:49
But I don’t know what the root cause is. I’ll look into when I get time if you guys can’t reproduce it.

**Comment by Martin-Idel-SI** [comment] 2018-06-29 07:52
That should be okay, yes.

I've seen the dummy robot in the past, too, but I can't run the launch file currently (probably have to update my installation). We'll definitely look into it on Monday.

But when the map frame prints out "error transforming" then we must hit this line: https://github.com/ros2/rviz/blob/6b0d290efe0be2875c5bbafd70936bf8a5721d53/rviz_default_plugins/src/rviz_default_plugins/displays/map/map_display.cpp#L544 which implies that some transforms failed.

**Comment by Martin-Idel-SI** [comment] 2018-07-02 07:52
I updated my ros installation and can now reproduce. 

In the debugger, the error thrown that leads the map (or LaserScanDisplay) to not show anything is here:

https://github.com/ros2/geometry2/blob/e9861210b1e5c905fea7da5c21b6990bdfe64648/tf2/src/buffer_core.cpp#L678

I get several different errors (not sure when I get which errors). When map is not showing, I get
`Could not find a connection between 'world' and 'single_rrbot_hokuyo_link' because they are not part of the same tree.Tf has two or more unconnected trees.`

So to me, this seems to be either a bug in TF or the robot doesn't publish its transforms correctly.

I also sometimes get a flickering laser scan (including a map) with the errors:
`Lookup would require extrapolation into the future.  Requested time 1530519582,77282 but the latest data is at time 1530519580,63707, when looking up transform from frame [world] to frame [single_rrbot_hokuyo_link]`

If I remember correctly, this is a problem in `laser_scan_display`: A laser scan needs to have transforms available for quite some time and previously, message filters made sure that this happened before letting the message through. Since `message_filters` aren't ported, yet, there is not much we can do.

In RViz, here is what we should do:
* We should definitely show the user there is a problem also in the LaserScanDisplay
* We might also want to log the exact error message to the console or even to the status message, but I'm not sure whether it helps to have the exact TF error message in the RViz status.
* We could also always show the TF error in the status message, but that's a bit more work, because we need to adjust the interface of `frame_manager`.

**Comment by Martin-Idel-SI** [comment] 2018-07-03 08:22
After a few more tries and working a bit more with logging, I can get a consistent picture:

The problem is indeed the error message
```
Lookup would require extrapolation into the future. Requested time 1530519582,77282 but the latest data is at time 1530519580,63707, when looking up transform from frame [world] to frame [single_rrbot_hokuyo_link]
```
So it's a mismatch of transformation data.

From my understanding, this was previously handled by message filters, which would allow a certain tolerance to deal with transforms (see https://answers.ros.org/question/217429/use-cases-for-tfmessagefiltersettolerance/). Since message filters aren't available yet the tolerance feature had to be disabled (see the TODO here: https://github.com/ros2/rviz/blob/6b0d290efe0be2875c5bbafd70936bf8a5721d53/rviz_default_plugins/src/rviz_default_plugins/displays/laser_scan/laser_scan_display.cpp#L62), I don't have any good solution for this issue right now.

What I don't understand though is that the map is also not displayed (extrapolation into the future) if my fixed frame is the `single_rrobot_link3` or the camera or laser scan frame. I would have expected tf to allow a transform between world and dynamic frame `/single_rrobot_link3`, but calling `lookupTransform` throws an extrapolation exception, too (and therefore, you see the error `[rviz2]: Error transforming map 'Map' from frame 'world' to 'single_rrobot_link3'.

The three bullet points in my previous message still apply.

**Comment by robotpilot** [comment] 2018-08-17 01:26
FYI, I can't see the laser data on rviz2 even if the fixed frame is the same as the frame_id of node of laser scanner.

**Comment by wjwwood** [comment] 2018-08-17 01:29
@robotpilot we need more info for that to be useful information (it might be a different issue). Which version of ROS 2/rviz are you using and are there any messages on the console that indicate a problem?

**Comment by robotpilot** [comment] 2018-08-17 02:04
[Case 1]
- `Ubuntu 16.04`
- `ROS2 Bouncy Bolson` (build from source code)
- Used packages: `dummy_robot_bringup` and `rviz2`

```
$ ros2 launch dummy_robot_bringup dummy_robot_bringup.launch.py
```
```
$ rviz2
```
I am also in the same state as you. The laser scans not showing when fixed frame is not equal to the frame_id of laser scans. In addition, setting the fixed frame to world, single_rrbot_link1, and single_rrbot_link2 did not show the laser value. So I set it to single_rrbot_link3, single_rrbot_camera_link, single_rrbot_hokuyo_link, and I could see the laser value at rviz2.

[Case 2]
- `Ubuntu 16.04`
- `ROS2 Bouncy Bolson` (build from source code)
- Used packages: [hls_lfcd_lds_driver for ROS2](https://github.com/ROBOTIS-GIT/hls_lfcd_lds_driver/tree/ros2) and `rviz2`

```
$ ros2 run hls_lfcd_lds_driver hlds_laser_publisher
```
```
$ ros2 topic echo /scan

header:
  stamp:
    sec: 1534470809
    nanosec: 149773231
  frame_id: laser
angle_min: 0.0
angle_max: 6.2657318115234375
angle_increment: 0.01745329238474369
time_increment: 2.9930000891909003e-05
scan_time: 0.0
range_min: 0.11999999731779099
range_max: 3.5
ranges: [0.6909999847412109, 0.6710000038146973, 0.671999990940094, 0.6399999856948853, 0.5899999737739563, 0.5590000152587891, 0.5389999747276306, 0.531000018119812, 0.5230000019073486, ....
```
```
$ rviz2
```
I can't see the laser data on rviz2 even if the fixed frame is the same as the frame_id of topic of /scan. 

The status of rviz2 is `Ok` and it says `xxxxx message received`, but the Points field just says `Showing [0] points from [0] messages`.
![rviz2_laserscan](https://user-images.githubusercontent.com/2698667/44244019-d2846780-a20c-11e8-9b34-3cfbed8098af.png)

**Comment by robotpilot** [comment] 2018-08-17 05:03
[case 3]

FYI, I have only run `dummy_laser` in the `dummy_sensors` package, but I could not see the laser value on rviz. (setting: Fixed Frame `single_rrbot_hokuyo_link`)

```
$ ros2 run dummy_sensors dummy_laser
```
```
$ ros2 topic echo /scan

header:
  stamp:
    sec: 1534481872
    nanosec: 924202607
  frame_id: single_rrbot_hokuyo_link
angle_min: -2.356194496154785
angle_max: 2.356194496154785
angle_increment: 0.004363323096185923
time_increment: 2.7777778086601757e-05
scan_time: 0.03999999910593033
range_min: 0.0
range_max: 10.0
ranges: [0.251274436712265, 0.251274436712265, 0.251274436712265, 0.251274436712265, 0.251274436712265, 0.251274436712265, ......
```
```
$ rviz2
```

**Comment by robotpilot** [comment] 2018-08-17 05:20
[successful case]

I hope this test will help you with your work. Based on the comments mentioned above, I ran the `static_transform_publisher` node to connect the `world` tf and the `laser` tf. I was able to check the laser value as shown in the attached figure below.

```
$ ros2 run hls_lfcd_lds_driver hlds_laser_publisher
```
```
$ ros2 topic echo /scan

header:
  stamp:
    sec: 1534483228
    nanosec: 725575168
  frame_id: laser
angle_min: 0.0
angle_max: 6.2657318115234375
angle_increment: 0.01745329238474369
time_increment: 2.9909999284427613e-05
scan_time: 0.0
range_min: 0.11999999731779099
range_max: 3.5
ranges: [1.3600000143051147, 1.4429999589920044, 1.5329999923706055, 1.5880000591278076, 1.5440000295639038, 1.5499999523162842, 1.534000039100647,......
```
```
$ ros2 run tf2_ros static_transform_publisher 0 0 0 0 0 0 world laser
```
```
$ rviz2
```
![case4](https://user-images.githubusercontent.com/2698667/44248949-74657d80-a228-11e8-860a-16eadfbe57f9.png)

**Comment by shiveshkhaitan** [comment] 2019-02-06 17:06
The error persists in crystal as well. This would probably be fixed after this [PR](https://github.com/ros2/rviz/pull/375) is merged. I could get Laser scans and Map in both the frames after implementing message filters.

**Comment by jacobperron** [comment] 2019-08-07 19:05
Since #375 has been merged, following the steps to reproduce, I can now see the laser scan in all frames. But, I am unable to see the map when switching to the frames that are not static wrt `world`, ie. `single_rrbot_hokuyo_link`, `single_rrbot_camera_link`, `single_rrbot_link2`, and `single_rrbot_link3`.

I get the error:

```
[ERROR] [rviz2]: Lookup would require extrapolation into the future.  Requested time 1565204390.71718 but the latest data is at time 1565204390.71718, when looking up transform from frame [single_rrbot_hokuyo_link] to frame [world]
```

**Comment by emersonknapp** [comment] 2019-10-10 21:30
> But, I am unable to see the map when switching to the frames that are not static wrt world

@jacobperron @wjwwood do you think the map display  issue should be tracked as a new issue, and this one closed out since the specific case of "laser scans not showing" has been resolved?

**Comment by wjwwood** [comment] 2019-10-10 23:48
I mean we can close this and open a new one, but the issue @jacobperron is describing makes me think that there is some lingering issue with #375... It should not even try to extrapolate into the future, in fact the data should never be delivered unless it could be transformed without extrapolation.

**Comment by emersonknapp** [comment] 2019-10-11 21:19
Ok! Just wanted to make sure we were tracking the right thing

**Comment by jacobperron** [comment] 2019-11-27 00:26
See https://github.com/ros2/rviz/pull/483 for a fix.

**Closed as completed** 2019-12-02 20:56 UTC
Labels: bug, help wanted
