### ISSUE TITLE
rviz error when creating a map using slam toolbox

### ISSUE THREAD

**Issue by koa-ellie** [ros2/rviz#1309] opened 2024-12-08 03:26 UTC
Hello everyone I'm using
Ubuntu 24.04.1
Jazzy Jalisco

[ERROR] [1733616056.993160004] [rviz2]: rviz/glsl120/indexed_8bit_image.vert
rviz/glsl120/indexed_8bit_image.frag
 GLSL link result : 
active samplers with a different type refer to the same texture image unit

**Comment by james-yoo** [comment] 2024-12-09 05:15
Same here

**Comment by Yadunund** [comment] 2024-12-09 06:13
Duplicate of https://github.com/ros2/rviz/issues/1279. I'll close this one so that we can track the discussion in the original ticket. It would be good if you could comment on whether you're also using an ARM device like the RPi 5.

**Closed as completed by Yadunund** 2024-12-09 06:13 UTC
