### ISSUE TITLE
Compilation failure of ROS2 Gallactiv: rviz_ogre_vendor  

### ISSUE THREAD

**Issue by nitin5** [ros2/rviz#713] opened 2021-06-22 06:16 UTC
OS: Ubuntu 20.04 

I am following the instruction for compilation of ROS2 Gallactic from [official webpage](https://docs.ros.org/en/galactic/Installation/Ubuntu-Development-Setup.html). I am facing the following linking error during the compilation. It appear that OGRE version is mismatching with requirement.
Current installed version is lib-OGRE1.12 (1.12.4+dfsg1-4) from official Ubuntu release debs.

rviz_ogre_vendor                                                                                           
/usr/bin/ld: ../../lib/libOgreMain.so.1.12.1: undefined reference to `Ogre::GpuProgramManager::getByName(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
/usr/bin/ld: ../../lib/libOgreMain.so.1.12.1: undefined reference to `Ogre::GpuProgramManager::getSingleton()'
/usr/bin/ld: ../../lib/libOgreMain.so.1.12.1: undefined reference to `Ogre::ArchiveManager::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
/usr/bin/ld: ../../lib/libOgreMain.so.1.12.1: undefined reference to `Ogre::ArchiveManager::ArchiveManager()'
/usr/bin/ld: ../../lib/libOgreMain.so.1.12.1: undefined reference to `Ogre::ArchiveManager::getSingleton()'
/usr/bin/ld: ../../lib/libOgreMain.so.1.12.1: undefined reference to `Ogre::ArchiveManager::addArchiveFactory(Ogre::ArchiveFactory*)'
collect2: error: ld returned 1 exit status
make[5]: *** [Tools/VRMLConverter/CMakeFiles/VRMLConverter.dir/build.make:175: bin/VRMLConverter] Error 1
make[4]: *** [CMakeFiles/Makefile2:1464: Tools/VRMLConverter/CMakeFiles/VRMLConverter.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....
/usr/bin/ld: ../../lib/libOgreMain.so.1.12.1: undefined reference to `Ogre::GpuProgramManager::getByName(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
/usr/bin/ld: ../../lib/libOgreMain.so.1.12.1: undefined reference to `Ogre::GpuProgramManager::getSingleton()'
/usr/bin/ld: ../../lib/libOgreMain.so.1.12.1: undefined reference to `Ogre::ArchiveManager::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
/usr/bin/ld: ../../lib/libOgreMain.so.1.12.1: undefined reference to `Ogre::ArchiveManager::ArchiveManager()'
/usr/bin/ld: ../../lib/libOgreMain.so.1.12.1: undefined reference to `Ogre::ArchiveManager::getSingleton()'
/usr/bin/ld: ../../lib/libOgreMain.so.1.12.1: undefined reference to `Ogre::ArchiveManager::addArchiveFactory(Ogre::ArchiveFactory*)'
collect2: error: ld returned 1 exit status
make[5]: *** [Tools/MeshUpgrader/CMakeFiles/OgreMeshUpgrader.dir/build.make:86: bin/OgreMeshUpgrader] Error 1
make[4]: *** [CMakeFiles/Makefile2:1437: Tools/MeshUpgrader/CMakeFiles/OgreMeshUpgrader.dir/all] Error 2
/usr/bin/ld: ../../lib/libOgreMain.so.1.12.1: undefined reference to `Ogre::GpuProgramManager::getByName(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
/usr/bin/ld: ../../lib/libOgreMain.so.1.12.1: undefined reference to `Ogre::GpuProgramManager::getSingleton()'
/usr/bin/ld: ../../lib/libOgreMain.so.1.12.1: undefined reference to `Ogre::ArchiveManager::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
/usr/bin/ld: ../../lib/libOgreMain.so.1.12.1: undefined reference to `Ogre::ArchiveManager::ArchiveManager()'
/usr/bin/ld: ../../lib/libOgreMain.so.1.12.1: undefined reference to `Ogre::ArchiveManager::getSingleton()'
/usr/bin/ld: ../../lib/libOgreMain.so.1.12.1: undefined reference to `Ogre::ArchiveManager::addArchiveFactory(Ogre::ArchiveFactory*)'
collect2: error: ld returned 1 exit status
make[5]: *** [Tools/XMLConverter/CMakeFiles/OgreXMLConverter.dir/build.make:176: bin/OgreXMLConverter] Error 1
make[4]: *** [CMakeFiles/Makefile2:1409: Tools/XMLConverter/CMakeFiles/OgreXMLConverter.dir/all] Error 2
make[3]: *** [Makefile:152: all] Error 2
make[2]: *** [CMakeFiles/ogre-v1.12.1.dir/build.make:116: ogre-v1.12.1-prefix/src/ogre-v1.12.1-stamp/ogre-v1.12.1-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:78: CMakeFiles/ogre-v1.12.1.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

Kindly advice the solution

**Comment by clalancette** [comment] 2021-06-23 13:43
Please don't open duplicate questions on multiple different repositories; this one is a duplicate of https://github.com/ros2/ros2/issues/1153 , so I'm closing.

**Closed as completed by clalancette** 2021-06-23 13:43 UTC
