### ISSUE TITLE
Explicit roadmap for InteractiveMarkers?

### ISSUE THREAD

**Issue by EricCousineau-TRI** [ros2/rviz#391] opened 2019-04-10 23:03 UTC
We have an application for using interactive markers in ROS1, and at some point, I'd like us to be able to migrate to using ROS2 if possible. One blocker is the lack of interactive markers.

Can I ask if anyone is actively working on this? If not, I'd be happy to spike-test it.
I can validate it by enabling and upgrading the ROS2 version of `visualization_tutorials`, along the same vein as this PR:
https://github.com/ros-visualization/visualization_tutorials/pull/49

**Comment by jacobperron** [comment] 2019-07-02 22:53
Duplicate of #98 

---

I've started the migration.

**Closed as completed by jacobperron** 2019-07-02 22:53 UTC
Labels: enhancement
