### ISSUE TITLE
Decreased performance in ros2-foxy versus ros2-dashing

### ISSUE THREAD

**Issue by simulacrus** [ros2/rviz#773] opened 2021-09-23 12:48 UTC
Hardware:
1. OS - ubuntu 20.04 / ubuntu 18.04
2. CPU - cpu intel core i7
3. GPU - Nvidia geforce gtx 250 (+proprietary driver)

Tests were carried out with the display of a large point cloud in version ros2-dashing (ubuntu 18) and version ros2-foxy (ubuntu 20). Statistics were collected on the duration of the renderOneFrame () function (file rviz2 / rviz_common / src / rviz_common / visualization_manager.cpp, line 437).

# ros2-dashing 
![dashing_after](https://user-images.githubusercontent.com/79246839/134509020-6d568df8-b08d-45dd-a3d0-a6e7c2e87217.png)

# ros2-foxy
![foxy_after](https://user-images.githubusercontent.com/79246839/134509145-e93a30f8-f4a2-4458-a6b2-cebbf06f92f9.png)

Why is that?

**Comment by gbalke** [comment] 2021-10-07 23:14
I'm trying to debug this. Do you have a share-able bag file?

**Comment by simulacrus** [comment] 2021-10-11 12:56
> I'm trying to debug this. Do you have a share-able bag file?

https://github.com/simulacrus/map/blob/main/testMap.tar.xz

**Comment by gbalke** [comment] 2021-10-13 00:32
Since this is a bit of a long debug, I thought I should document my steps in case someone else wants to take a look (and for reference in future debugs).

I've used [uftrace](https://github.com/namhyung/uftrace) to follow all calls to `rviz_rendering::PointCloud*` using the following commands:

``` shell
# Build with instrumentation flags
$ colcon build --symlink-install --cmake-args -DBUILD_TESTING:=OFF -DCMAKE_CXX_FLAGS:=-pg -DCMAKE_EXE_LINKER_FLAGS=-pg -DCMAKE_SHARED_LINKER_FLAGS=-pg
# Source install
$ source install/setup.sh
# Run uftrace (make sure you're going to be using the correct version of rviz with `which rviz2`)
$ uftrace record -F rviz_rendering::PointCloud* rviz2 -d ../../map.rviz
```

While the recorder is running, I run some replay from the bag. I found that rviz doesn't seem to register the single frame playback so I loop and exit as soon as rviz locks up (2-4 loops should do the trick).

```
ros2 bag play testmap/ -l
```

This locks up rviz for a minute... This isn't as bad when not instrumented. Eventually the pointcloud should appear:
![image](https://user-images.githubusercontent.com/11024792/137043121-ef8bbbbd-8816-4c3a-ad10-98a41f50e401.png)

At this point, close rviz and a `uftrace.data` folder should be in the current directory. Running `uftrace report` will generate the amount of time spent in each function call. This data will take a lot of time to accumulate as this is an absurd number of function calls that were recorded.

This in fact takes so long that it may not be worth checking (my trace broke 100GB when expanded to a json). In the hopes that this is not an issue caused at scale but instead individual paths, I reran with the point cloud generator made for #752 which generated a much more reasonably sized report.

``` shell
uftrace replay -F rviz_rendering::PointCloud::addPoints -t 1ms
# DURATION     TID     FUNCTION
            [126327] | rviz_rendering::PointCloud::addPoints() {
            [126327] |   std::vector::insert() {
            [126327] |     std::vector::_M_insert_dispatch() {
            [126327] |       std::vector::_M_range_insert() {
            [126327] |         std::__uninitialized_copy_a() {
            [126327] |           std::uninitialized_copy() {
   1.047 ms [126327] |             std::__uninitialized_copy::__uninit_copy();
   1.048 ms [126327] |           } /* std::uninitialized_copy */
   1.049 ms [126327] |         } /* std::__uninitialized_copy_a */
   1.065 ms [126327] |       } /* std::vector::_M_range_insert */
   1.067 ms [126327] |     } /* std::vector::_M_insert_dispatch */
   1.074 ms [126327] |   } /* std::vector::insert */
  25.191 ms [126327] | } /* rviz_rendering::PointCloud::addPoints */
```

The original test cloud is 1000 points so I doubled it to 2000 points and noticed these results:
``` shell
# DURATION     TID     FUNCTION
            [126481] | rviz_rendering::PointCloud::addPoints() {
            [126481] |   std::vector::insert() {
            [126481] |     std::vector::_M_insert_dispatch() {
            [126481] |       std::vector::_M_range_insert() {
            [126481] |         std::__uninitialized_copy_a() {
            [126481] |           std::uninitialized_copy() {
   1.557 ms [126481] |             std::__uninitialized_copy::__uninit_copy();
   1.558 ms [126481] |           } /* std::uninitialized_copy */
   1.559 ms [126481] |         } /* std::__uninitialized_copy_a */
   1.575 ms [126481] |       } /* std::vector::_M_range_insert */
   1.577 ms [126481] |     } /* std::vector::_M_insert_dispatch */
   1.583 ms [126481] |   } /* std::vector::insert */
  47.869 ms [126481] | } /* rviz_rendering::PointCloud::addPoints */
```

Digging a little deeper with `uftrace replay -F rviz_rendering::PointCloud::addPoints -D 3 -t 1us` I found this looping for what seems like forever. I assume this is an O(N) operation where N=number of points. Multiplying this out (~20us) by the 2k points gives us 40ms.
``` shell
          [126481] |   rviz_rendering::PointCloud::RenderableInternals::operator=() {
 1.563 us [126481] |     std::shared_ptr::operator=();
 1.643 us [126481] |   } /* rviz_rendering::PointCloud::RenderableInternals::operator= */
 1.853 us [126481] |   Ogre::AxisAlignedBox::merge();
16.231 us [126481] |   rviz_rendering::PointCloud::addPointToHardwareBuffer();
 ```

Further diving in `uftrace replay -F rviz_rendering::PointCloud::addPointToHardwareBuffer -D 5` shows:
``` shell
            [126481] | rviz_rendering::PointCloud::addPointToHardwareBuffer() {
            [126481] |   rviz_rendering::PointCloudRenderable::getBuffer() {
            [126481] |     Ogre::SharedPtr::SharedPtr() {
   0.541 us [126481] |       std::shared_ptr::shared_ptr();
   0.611 us [126481] |     } /* Ogre::SharedPtr::SharedPtr */
   0.691 us [126481] |   } /* rviz_rendering::PointCloudRenderable::getBuffer */
            [126481] |   Ogre::SharedPtr::~SharedPtr() {
   0.531 us [126481] |     std::shared_ptr::~shared_ptr();
   0.611 us [126481] |   } /* Ogre::SharedPtr::~SharedPtr */
            [126481] |   rviz_rendering::PointCloudRenderable::getBuffer() {
            [126481] |     Ogre::SharedPtr::SharedPtr() {
   0.541 us [126481] |       std::shared_ptr::shared_ptr();
   0.611 us [126481] |     } /* Ogre::SharedPtr::SharedPtr */
   0.691 us [126481] |   } /* rviz_rendering::PointCloudRenderable::getBuffer */
            [126481] |   Ogre::SharedPtr::~SharedPtr() {
   0.531 us [126481] |     std::shared_ptr::~shared_ptr();
   0.612 us [126481] |   } /* Ogre::SharedPtr::~SharedPtr */
            [126481] |   rviz_rendering::PointCloudRenderable::getBuffer() {
            [126481] |     Ogre::SharedPtr::SharedPtr() {
   0.531 us [126481] |       std::shared_ptr::shared_ptr();
   0.601 us [126481] |     } /* Ogre::SharedPtr::SharedPtr */
   0.682 us [126481] |   } /* rviz_rendering::PointCloudRenderable::getBuffer */
            [126481] |   Ogre::SharedPtr::~SharedPtr() {
   0.521 us [126481] |     std::shared_ptr::~shared_ptr();
   0.591 us [126481] |   } /* Ogre::SharedPtr::~SharedPtr */
            [126481] |   rviz_rendering::PointCloudRenderable::getBuffer() {
            [126481] |     Ogre::SharedPtr::SharedPtr() {
   0.531 us [126481] |       std::shared_ptr::shared_ptr();
   0.611 us [126481] |     } /* Ogre::SharedPtr::SharedPtr */
   0.691 us [126481] |   } /* rviz_rendering::PointCloudRenderable::getBuffer */
            [126481] |   Ogre::SharedPtr::~SharedPtr() {
   0.511 us [126481] |     std::shared_ptr::~shared_ptr();
   0.581 us [126481] |   } /* Ogre::SharedPtr::~SharedPtr */
            [126481] |   rviz_rendering::PointCloudRenderable::getBuffer() {
            [126481] |     Ogre::SharedPtr::SharedPtr() {
   0.541 us [126481] |       std::shared_ptr::shared_ptr();
   0.611 us [126481] |     } /* Ogre::SharedPtr::SharedPtr */
   0.691 us [126481] |   } /* rviz_rendering::PointCloudRenderable::getBuffer */
            [126481] |   Ogre::SharedPtr::~SharedPtr() {
   0.510 us [126481] |     std::shared_ptr::~shared_ptr();
   0.582 us [126481] |   } /* Ogre::SharedPtr::~SharedPtr */
            [126481] |   rviz_rendering::PointCloudRenderable::getBuffer() {
            [126481] |     Ogre::SharedPtr::SharedPtr() {
   0.531 us [126481] |       std::shared_ptr::shared_ptr();
   0.612 us [126481] |     } /* Ogre::SharedPtr::SharedPtr */
   0.692 us [126481] |   } /* rviz_rendering::PointCloudRenderable::getBuffer */
            [126481] |   Ogre::SharedPtr::~SharedPtr() {
   0.511 us [126481] |     std::shared_ptr::~shared_ptr();
   0.581 us [126481] |   } /* Ogre::SharedPtr::~SharedPtr */
   0.511 us [126481] |   rviz_rendering::PointCloud::RenderableInternals::RenderableInternals();
  16.421 us [126481] | } /* rviz_rendering::PointCloud::addPointToHardwareBuffer */
```

There appear to be numerous creations/deletions of Ogre SharedPtr instances. These seem to be adding up to a whole lot of compute time. I'll dive in to the code tomorrow and also run the same analysis on Dashing.

**Comment by gbalke** [comment] 2021-10-13 21:51
I managed to reduce this time in half by moving the `getBuffer()` out of the assert and previous to the for loop. This, however, does not particularly improve the scenario as this is a different path from what we expect when running in release mode (assert is not run in release). If I change my build to:
```
colcon build --merge-install --cmake-args -DBUILD_TESTING:=OFF -DCMAKE_CXX_FLAGS:=-pg -DCMAKE_EXE_LINKER_FLAGS=-pg -DCMAKE_SHARED_LINKER_FLAGS=-pg -DCMAKE_BUILD_TYPE=Release
```
The execution of AddPoints drops down to 5ms for a 2000 point point cloud (not accounting for overhead). For 100k points, adding the points takes about 100ms.

@simulacrus at this point, it would be good to know if you're running on a release of rviz or if you're running a local build without the release flag? I'll be digging into Dashing while waiting for a response.

**Comment by gbalke** [comment] 2021-10-14 20:05
After comparing the results of Dashing and Foxy for point cloud addition, I can say they are approximately the same if not faster for Foxy. This leads me to believe that either the build is not in release mode or something else is causing the slowdown. I'll see which other pipelines may be having issues (though this already puts the frame rate below 10fps so I'm pretty confident this is a/the significant bottleneck).

# Foxy Results
``` shell
# DURATION     TID     FUNCTION
            [136954] | rviz_rendering::PointCloud::addPoints() {
   2.027 ms [136954] |   rviz_rendering::PointCloud::createNewRenderable();
 105.236 ms [136954] | } /* rviz_rendering::PointCloud::addPoints */
  98.154 ms [136954] | rviz_rendering::PointCloud::addPoints();
  98.350 ms [136954] | rviz_rendering::PointCloud::addPoints();
  99.076 ms [136954] | rviz_rendering::PointCloud::addPoints();
  98.825 ms [136954] | rviz_rendering::PointCloud::addPoints();
  98.633 ms [136954] | rviz_rendering::PointCloud::addPoints();
  98.002 ms [136954] | rviz_rendering::PointCloud::addPoints();
  98.196 ms [136954] | rviz_rendering::PointCloud::addPoints();
```

# Dashing Results
``` shell
            [ 14634] | rviz_rendering::PointCloud::addPoints() {
   4.595 ms [ 14634] |   rviz_rendering::PointCloud::createNewRenderable();
   2.825 ms [ 14634] |   rviz_rendering::PointCloud::createNewRenderable();
 116.321 ms [ 14634] | } /* rviz_rendering::PointCloud::addPoints */
            [ 14634] | rviz_rendering::PointCloud::addPoints() {
   4.466 ms [ 14634] |   rviz_rendering::PointCloud::createNewRenderable();
 115.135 ms [ 14634] | } /* rviz_rendering::PointCloud::addPoints */
            [ 14634] | rviz_rendering::PointCloud::addPoints() {
   1.239 ms [ 14634] |   rviz_rendering::PointCloud::createNewRenderable();
 116.533 ms [ 14634] | } /* rviz_rendering::PointCloud::addPoints */
            [ 14634] | rviz_rendering::PointCloud::addPoints() {
   1.339 ms [ 14634] |   rviz_rendering::PointCloud::createNewRenderable();
 110.312 ms [ 14634] | } /* rviz_rendering::PointCloud::addPoints */
            [ 14634] | rviz_rendering::PointCloud::addPoints() {
   1.241 ms [ 14634] |   rviz_rendering::PointCloud::createNewRenderable();
 110.007 ms [ 14634] | } /* rviz_rendering::PointCloud::addPoints */
            [ 14634] | rviz_rendering::PointCloud::addPoints() {
   1.302 ms [ 14634] |   rviz_rendering::PointCloud::createNewRenderable();
 106.404 ms [ 14634] | } /* rviz_rendering::PointCloud::addPoints */
            [ 14634] | rviz_rendering::PointCloud::addPoints() {
   1.256 ms [ 14634] |   rviz_rendering::PointCloud::createNewRenderable();
 106.373 ms [ 14634] | } /* rviz_rendering::PointCloud::addPoints */
```

**Comment by jcaraban** [comment] 2021-10-15 06:24
@gbalke I believe the rviz2 foxy releases are not compiled with optimizations...
I cloned and compiled the foxy branch with optimizations, and it runs 2~3x faster in my use case and machine.

note: my use case has no point clouds, just a few thousand different markers

**Comment by gbalke** [comment] 2021-10-15 06:27
> I cloned and compiled the foxy branch with optimizations, and it runs 2~3x faster in my use case and machine.

Which optimizations? -O flags or the release flag?

**Comment by jcaraban** [comment] 2021-10-15 06:45
I guess by _release flag_ you mean `-DCMAKE_BUILD_TYPE=Release` ? My understanding is that cmake will use `-O3` for the Release build type. However, by default colcon doesn't seem to set any cmake build type, which ends up `-O0`

When looking at the assembly of `/opt/ros/foxy/bin/rviz2` vs my compiled rviz2 binary, the latter weights 31K and has a few SSE instructions, while the former is 23K with no xmm registers anywhere. However the rest of the code doesn't look so different...

_edit:_ I compiled with no optimizations and got a fat 97K binary, but the performance was almost on par with `/opt/ros/foxy/bin/rviz2`. I also compiled  in MinSizeRel with noticeable better performance again.

**Comment by clalancette** [comment] 2021-10-15 12:49
Just to be clear; when we are building the binaries for release on the buildfarm, `colcon` isn't involved at all.  We directly invoke CMake (well, we invoke it through the debian build helper scripts).  You can see it in action in e.g. https://build.ros2.org/job/Fbin_uF64__rviz_common__ubuntu_focal_amd64__binary/106/consoleFull .

I haven't looked in detail into what is happening in those builds.  Maybe we aren't setting `-DCMAKE_BUILD_TYPE=Release` when building for packages, or we maybe we're missing platform-specific flags (to enable SSE and the like) which would help a lot.

In either case, that's where I would look next.

**Comment by simulacrus** [comment] 2021-10-15 13:00
So...I try to turn off Selectable option on pointcloud2 plugin and ... it work. Stable 60+ fps. Why is that? 
P.S.
For more computationally expensive test try to increase size(pixels) option value

**Comment by gbalke** [comment] 2021-10-15 18:17
#670 claims issue with selecting on large point clouds. This seems to support that claim. I'll take a closer look at that pipeline! Maybe they're the same issue :monocle_face:

**Comment by gbalke** [comment] 2021-10-18 18:44
When I selected a large region of the point cloud (about 1/8 of a 100k point cloud), there was a large delay and then update time took an additional 40ms:


```shell
            [ 21299] |     rviz_common::VisualizationManager::qt_static_metacall() {
            [ 21299] |       rviz_common::VisualizationManager::onUpdate() {
  93.716 ms [ 21299] |         rviz_common::DisplayGroup::update();
 103.096 ms [ 21299] |       } /* rviz_common::VisualizationManager::onUpdate */
 103.096 ms [ 21299] |     } /* rviz_common::VisualizationManager::qt_static_metacall */
            [ 21299] |     rviz_common::_RosTopicDisplay::qt_static_metacall() {
            [ 21299] |       rviz_common::MessageFilterDisplay::processTypeErasedMessage() {
  11.517 ms [ 21299] |         rviz_default_plugins::displays::PointCloud2Display::processMessage();
  11.524 ms [ 21299] |       } /* rviz_common::MessageFilterDisplay::processTypeErasedMessage */
  11.525 ms [ 21299] |     } /* rviz_common::_RosTopicDisplay::qt_static_metacall */
            [ 21299] |     rviz_common::VisualizationManager::qt_static_metacall() {
            [ 21299] |       rviz_common::VisualizationManager::onUpdate() {
  94.063 ms [ 21299] |         rviz_common::DisplayGroup::update();
 104.047 ms [ 21299] |       } /* rviz_common::VisualizationManager::onUpdate */
 104.047 ms [ 21299] |     } /* rviz_common::VisualizationManager::qt_static_metacall */
            [ 21299] |     rviz_rendering::RenderWindow::event() {
            [ 21299] |       std::_Function_handler::_M_invoke() {
   1.410  s [ 21299] |         rviz_common::RenderPanel::onRenderWindowMouseEvents();
   1.410  s [ 21299] |       } /* std::_Function_handler::_M_invoke */
   1.410  s [ 21299] |     } /* rviz_rendering::RenderWindow::event */
            [ 21299] |     rviz_common::_RosTopicDisplay::qt_static_metacall() {
            [ 21299] |       rviz_common::MessageFilterDisplay::processTypeErasedMessage() {
  12.745 ms [ 21299] |         rviz_default_plugins::displays::PointCloud2Display::processMessage();
  12.753 ms [ 21299] |       } /* rviz_common::MessageFilterDisplay::processTypeErasedMessage */
  12.754 ms [ 21299] |     } /* rviz_common::_RosTopicDisplay::qt_static_metacall */
            [ 21299] |     rviz_common::VisualizationManager::qt_static_metacall() {
            [ 21299] |       rviz_common::VisualizationManager::onUpdate() {
  98.374 ms [ 21299] |         rviz_common::DisplayGroup::update();
 434.175 ms [ 21299] |       } /* rviz_common::VisualizationManager::onUpdate */
 434.176 ms [ 21299] |     } /* rviz_common::VisualizationManager::qt_static_metacall */
            [ 21299] |     rviz_common::_RosTopicDisplay::qt_static_metacall() {
            [ 21299] |       rviz_common::MessageFilterDisplay::processTypeErasedMessage() {
  12.223 ms [ 21299] |         rviz_default_plugins::displays::PointCloud2Display::processMessage();
  12.231 ms [ 21299] |       } /* rviz_common::MessageFilterDisplay::processTypeErasedMessage */
  12.232 ms [ 21299] |     } /* rviz_common::_RosTopicDisplay::qt_static_metacall */
            [ 21299] |     rviz_common::VisualizationManager::qt_static_metacall() {
            [ 21299] |       rviz_common::VisualizationManager::onUpdate() {
  93.933 ms [ 21299] |         rviz_common::DisplayGroup::update();
 139.649 ms [ 21299] |       } /* rviz_common::VisualizationManager::onUpdate */
 139.650 ms [ 21299] |     } /* rviz_common::VisualizationManager::qt_static_metacall */
            [ 21299] |     rviz_common::_RosTopicDisplay::qt_static_metacall() {
            [ 21299] |       rviz_common::MessageFilterDisplay::processTypeErasedMessage() {
  11.270 ms [ 21299] |         rviz_default_plugins::displays::PointCloud2Display::processMessage();
  11.278 ms [ 21299] |       } /* rviz_common::MessageFilterDisplay::processTypeErasedMessage */
  11.279 ms [ 21299] |     } /* rviz_common::_RosTopicDisplay::qt_static_metacall */
            [ 21299] |     rviz_common::VisualizationManager::qt_static_metacall() {
            [ 21299] |       rviz_common::VisualizationManager::onUpdate() {
  95.349 ms [ 21299] |         rviz_common::DisplayGroup::update();
 145.320 ms [ 21299] |       } /* rviz_common::VisualizationManager::onUpdate */
 145.321 ms [ 21299] |     } /* rviz_common::VisualizationManager::qt_static_metacall */
```

__NOTE:__ The `onUpdate`/`qt_static_metacall` call stack leads down to `addPoints` (through a bunch of layers of function calls).
```shell
            [ 21299] | rviz_common::VisualizationManager::qt_static_metacall() {
            [ 21299] |   rviz_common::VisualizationManager::onUpdate() {
            [ 21299] |     rviz_common::DisplayGroup::update() {
            [ 21299] |       rviz_default_plugins::displays::PointCloud2Display::update() {
            [ 21299] |         rviz_default_plugins::PointCloudCommon::update() {
            [ 21299] |           rviz_default_plugins::PointCloudCommon::insertNewClouds() {
 111.829 ms [ 21299] |             rviz_rendering::PointCloud::addPoints();
 111.928 ms [ 21299] |           } /* rviz_default_plugins::PointCloudCommon::insertNewClouds */
 112.014 ms [ 21299] |         } /* rviz_default_plugins::PointCloudCommon::update */
 112.014 ms [ 21299] |       } /* rviz_default_plugins::displays::PointCloud2Display::update */
 112.024 ms [ 21299] |     } /* rviz_common::DisplayGroup::update */
 114.827 ms [ 21299] |   } /* rviz_common::VisualizationManager::onUpdate */
 114.827 ms [ 21299] | } /* rviz_common::VisualizationManager::qt_static_metacall */
```

**Comment by gbalke** [comment] 2021-10-18 18:54
> So...I try to turn off Selectable option on pointcloud2 plugin and ... it work. Stable 60+ fps. Why is that?

I disabled selectable and am still getting 0-1 fps:
![image](https://user-images.githubusercontent.com/11024792/137789960-23d5bb70-37f9-4b1f-8a72-487034124126.png)
 I have no idea what's going on here... Are you somehow selecting points without realizing it?

**Comment by simulacrus** [comment] 2021-10-18 19:50
> > So...I try to turn off Selectable option on pointcloud2 plugin and ... it work. Stable 60+ fps. Why is that?
> 
> I disabled selectable and am still getting 0-1 fps: ![image](https://user-images.githubusercontent.com/11024792/137789960-23d5bb70-37f9-4b1f-8a72-487034124126.png) I have no idea what's going on here... Are you somehow selecting points without realizing it?

Nope. Try to select Style Point and turn off autocompute option.

**Comment by gbalke** [comment] 2021-10-18 19:53
@simulacrus I was able to reproduce "performance gains" by having a large region selected when I turned off "selectable". This auto-deselects all regions that were selected. I think you might be selecting large regions which causes this performance hit. See this video. 

At the start of the video, I begin publishing your bag on loop as fast as it will publish. This causes RViz to perform very poorly as it is calling `addPoints` over and over again on an enormous point cloud. This has an unavoidably large overhead given the sheer volume of data (maybe there are optimizations to be made but I imagine it's a battle of diminishing returns when it comes to millions of points). I imagine this point cloud is, realistically, generated over time as the robot explores (with infinite lifetime on every point) so you won't/shouldn't be publishing the entire point cloud in a loop. When I kill the bag loop, FPS returns to a solid 30/31 (my RViz configuration caps at 30fps) while maintaining the entire point cloud. This tells me the issue is __not__ with the rendering pipeline. I then zoom into the point cloud and select a big chunk of it. This reduces the FPS to 7-8 which lets me know selecting is computationally intensive. I then disable the `Selectable` option in the PointCloud2 plugin and the region is de-selected as well as the frame rate returning to a stable 30fps. I repeat this once more for good measure :smile:.

https://user-images.githubusercontent.com/11024792/137796188-1234c98b-deeb-4682-a72f-47a59532cb08.mp4

Given these results, I have a feeling something strange is going on in your specific configuration/setup. Please let me know if there's anything else I should know as I think I've exhausted most paths to explore on my end. In the meantime, I'll focus on #670.

**Comment by gbalke** [comment] 2021-10-18 19:55
> Nope. Try to select Style Point and turn off autocompute option.

Same results with the following configuration:
![image](https://user-images.githubusercontent.com/11024792/137797895-958d7afc-d366-4bbd-8166-57a8724600c6.png)

**Comment by gbalke** [comment] 2021-11-04 19:49
@simulacrus I'm going to close this issue as a duplicate of #670. If you have additional information to add, please feel free to respond and the issue can be re-opened.

**Closed as completed by gbalke** 2021-11-04 19:49 UTC
