### ISSUE TITLE
RViz use custom shader for Mesh_Resource marker

### ISSUE THREAD

**Issue by Tingcccc** [ros2/rviz#560] opened 2020-06-04 09:37 UTC
Hello,
Could I use custom shader for mesh resource marker?
How do I add the shader code in Rviz then bind shader and mesh material?
Look forward to your reply. Thank you!

**Comment by sloretz** [comment] 2020-06-11 16:27
Hi @Tingcccc , this looks like a duplicate of #559. I'll close this one in favor of the first one.

**Closed as completed by sloretz** 2020-06-11 16:27 UTC
